// default package
// Generated 25/07/2015 18:50:24 by Hibernate Tools 3.2.2.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * InvoiceLine generated by hbm2java
 */
@Entity
@Table(name="invoice_line"
)
public class InvoiceLine  implements java.io.Serializable {


     private Long id;
     private Concept concept;
     private Invoice invoice;
     private Unit unit;
     private BigDecimal ammount;
     private String conceptDescription;
     private String description;
     private Integer qty;
     private Set<UnitValue> unitValues = new HashSet<UnitValue>(0);

    public InvoiceLine() {
    }

    public InvoiceLine(Concept concept, Invoice invoice, Unit unit, BigDecimal ammount, String conceptDescription, String description, Integer qty, Set<UnitValue> unitValues) {
       this.concept = concept;
       this.invoice = invoice;
       this.unit = unit;
       this.ammount = ammount;
       this.conceptDescription = conceptDescription;
       this.description = description;
       this.qty = qty;
       this.unitValues = unitValues;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="concept_id")
    public Concept getConcept() {
        return this.concept;
    }
    
    public void setConcept(Concept concept) {
        this.concept = concept;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="invoice_id")
    public Invoice getInvoice() {
        return this.invoice;
    }
    
    public void setInvoice(Invoice invoice) {
        this.invoice = invoice;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="unit_id")
    public Unit getUnit() {
        return this.unit;
    }
    
    public void setUnit(Unit unit) {
        this.unit = unit;
    }
    
    @Column(name="ammount")
    public BigDecimal getAmmount() {
        return this.ammount;
    }
    
    public void setAmmount(BigDecimal ammount) {
        this.ammount = ammount;
    }
    
    @Column(name="concept_description")
    public String getConceptDescription() {
        return this.conceptDescription;
    }
    
    public void setConceptDescription(String conceptDescription) {
        this.conceptDescription = conceptDescription;
    }
    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="qty")
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="invoiceLine")
    public Set<UnitValue> getUnitValues() {
        return this.unitValues;
    }
    
    public void setUnitValues(Set<UnitValue> unitValues) {
        this.unitValues = unitValues;
    }




}


