// default package
// Generated 25/07/2015 18:50:24 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Unit generated by hbm2java
 */
@Entity
@Table(name="unit"
)
public class Unit  implements java.io.Serializable {


     private Long id;
     private String description;
     private String name;
     private Integer operation;
     private Set<Concept> concepts = new HashSet<Concept>(0);
     private Set<UnitField> unitFields = new HashSet<UnitField>(0);
     private Set<InvoiceLine> invoiceLines = new HashSet<InvoiceLine>(0);

    public Unit() {
    }

    public Unit(String description, String name, Integer operation, Set<Concept> concepts, Set<UnitField> unitFields, Set<InvoiceLine> invoiceLines) {
       this.description = description;
       this.name = name;
       this.operation = operation;
       this.concepts = concepts;
       this.unitFields = unitFields;
       this.invoiceLines = invoiceLines;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="name")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="operation")
    public Integer getOperation() {
        return this.operation;
    }
    
    public void setOperation(Integer operation) {
        this.operation = operation;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="unit")
    public Set<Concept> getConcepts() {
        return this.concepts;
    }
    
    public void setConcepts(Set<Concept> concepts) {
        this.concepts = concepts;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="unit")
    public Set<UnitField> getUnitFields() {
        return this.unitFields;
    }
    
    public void setUnitFields(Set<UnitField> unitFields) {
        this.unitFields = unitFields;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="unit")
    public Set<InvoiceLine> getInvoiceLines() {
        return this.invoiceLines;
    }
    
    public void setInvoiceLines(Set<InvoiceLine> invoiceLines) {
        this.invoiceLines = invoiceLines;
    }




}


