// default package
// Generated 25/07/2015 18:50:24 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UnitField generated by hbm2java
 */
@Entity
@Table(name="unit_field"
)
public class UnitField  implements java.io.Serializable {


     private Long id;
     private Unit unit;
     private Boolean mandatory;
     private String name;
     private Set<UnitValue> unitValues = new HashSet<UnitValue>(0);

    public UnitField() {
    }

    public UnitField(Unit unit, Boolean mandatory, String name, Set<UnitValue> unitValues) {
       this.unit = unit;
       this.mandatory = mandatory;
       this.name = name;
       this.unitValues = unitValues;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="unit_id")
    public Unit getUnit() {
        return this.unit;
    }
    
    public void setUnit(Unit unit) {
        this.unit = unit;
    }
    
    @Column(name="mandatory")
    public Boolean getMandatory() {
        return this.mandatory;
    }
    
    public void setMandatory(Boolean mandatory) {
        this.mandatory = mandatory;
    }
    
    @Column(name="name")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="unitField")
    public Set<UnitValue> getUnitValues() {
        return this.unitValues;
    }
    
    public void setUnitValues(Set<UnitValue> unitValues) {
        this.unitValues = unitValues;
    }




}


